### ISSUE TITLE
qq oauth问题

### ISSUE THREAD

**Issue by alanljj** [bigfa/wp-oauth#1]
添加functions.php中的代码放到我的functions.php可以，但把qq.php放进去就会打不开页面，该如何查找问题？谢谢！

**Comment by bigfa** [comment]
你可以把`wp-config.php`里的debug设置为true，会提示哪的问题

**Comment by alanljj** [comment]
谢谢！这是提示，是和我的两个插件冲突吗？

Notice: Constant EZSQL_VERSION already defined in /geekerweb/gc/wp-content/db.php on line 43

Notice: Constant object already defined in /geekerweb/gc/wp-content/db.php on line 48

Notice: Constant OBJECT_K already defined in /geekerweb/gc/wp-content/db.php on line 53

Notice: Constant ARRAY_A already defined in /geekerweb/gc/wp-content/db.php on line 58

Notice: Constant ARRAY_N already defined in /geekerweb/gc/wp-content/db.php on line 63

Deprecated: Assigning the return value of new by reference is deprecated in /geekerweb/gc/wp-content/plugins/db-cache-reloaded-fix/db-module.php on line 214

Notice: Constant EZSQL_VERSION already defined in /geekerweb/gc/wp-content/plugins/db-cache-reloaded-fix/db-module.php on line 43

Notice: Constant object already defined in /geekerweb/gc/wp-content/plugins/db-cache-reloaded-fix/db-module.php on line 48

Notice: Constant OBJECT_K already defined in /geekerweb/gc/wp-content/plugins/db-cache-reloaded-fix/db-module.php on line 53

Notice: Constant ARRAY_A already defined in /geekerweb/gc/wp-content/plugins/db-cache-reloaded-fix/db-module.php on line 58

Notice: Constant ARRAY_N already defined in /geekerweb/gc/wp-content/plugins/db-cache-reloaded-fix/db-module.php on line 63

Deprecated: Assigning the return value of new by reference is deprecated in /geekerweb/gc/wp-content/plugins/db-cache-reloaded-fix/db-cache-reloaded.php on line 91

Parse error: syntax error, unexpected 'function' (T_FUNCTION) in /geekerweb/gc/wp-content/themes/dt-the7-child/functions.php on line 308

Notice: ob_end_flush(): failed to delete and flush buffer. No buffer to delete or flush in /geekerweb/gc/wp-content/plugins/wp-acceleration-for-china/wp-acceleration-for-china.php on line 49

**Comment by bigfa** [comment]
`Parse error: syntax error, unexpected 'function' (T_FUNCTION) in /geekerweb/gc/wp-content/themes/dt-the7-child/functions.php on line 308` 这句是错误原因，检查下是不是分号后者大括号的问题

**Comment by alanljj** [comment]
308行是：
function qq_oauth_url(){

似乎没什么问题

**Comment by bigfa** [comment]
看前面 - -  你这是语法错误

**Comment by alanljj** [comment]
我不太懂，只是copy了你的qq.php文件，请教应该怎样改？

**Comment by bigfa** [comment]
。。。函数应该放在`<?php` 和`?>`之间，建议了解下php语法再折腾

**Comment by alanljj** [comment]
我的确是不懂php的，看到function.php上面有个<?php开头，以为代码放到里面就可以了。
我是把你的qq和fun两个文件开头的<?php删除，然后放到自己的function.php，这样还不行的呀，见笑了！

**Comment by tuber** [comment]
get_url_contents 这个函数貌似没有

**Comment by tuber** [comment]
function get_url_contents($url){    
      if (function_exists('file_get_contents')) {    
        $result = @file_get_contents($url);    
      }    
      if ($result == '') {    
        $ch = curl_init();    
        $timeout = 30;    
        curl_setopt($ch, CURLOPT_URL, $url);    
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);   
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);  
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);  
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);  
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);    
        $result = curl_exec($ch);    
        curl_close($ch);    
      }    
        
      return $result;    
    }

**Comment by tuber** [comment]
另外，不知道你的记住登录在哪里设置的。
 wp_set_auth_cookie($user_id,true,false);
 wp_set_current_user($user_id);

**Comment by bigfa** [comment]
qq那个代码好早了，有空我重写下。。
