### ISSUE TITLE
不缓存accesstoken吗？

### ISSUE THREAD

**Issue by linzian** [bigfa/wp-oauth#4]
RT

**Comment by linzian** [comment]
关于微信的

**Comment by bigfa** [comment]
没必要

2016年8月4日星期四，linzian <notifications@github.com> 写道：

**Comment by linzian** [comment]
@bigfa 
accesstoken一天只能get2000次...而且获取后上一个accesstoken会失效会导致2个同时登陆的人，先点开登陆页面的人登陆失败..

**Comment by bigfa** [comment]
不明白你说的，token是用来获取用户资料的，实在不知道你说的是啥。

2016年8月4日星期四，linzian <notifications@github.com> 写道：

**Comment by linzian** [comment]
![QQ截图20160804163039.png](https://ooo.0o0.ooo/2016/08/04/57a2fd2caf666.png)
accesstoken一天只能获取2000次啊........

**Comment by bigfa** [comment]
那是微信的问题，你可以阅读下oauth的流程，获取token是必须的。

2016年8月4日星期四，linzian <notifications@github.com> 写道：

**Comment by linzian** [comment]
所以应该把AccessToken缓存起来啊......

**Comment by bigfa** [comment]
………随便吧，你乐意缓存就缓存。

2016年8月4日星期四，linzian <notifications@github.com> 写道：

**Comment by bigfa** [comment]
你可以仔细阅读文档，access_token分两种，oauth那个并没有限制。

2016年8月4日星期四，linzian <notifications@github.com> 写道：
